apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
#    - ReadWriteMany
    - ReadWriteOnce
#    - ReadOnlyMany
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi