apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
          - name: nginx
            image: nginx
            ports:
            - containerPort: 80
            volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html
            # These containers are run during pod initialization
      initContainers:
      - name: install
        image: busybox:1.28
        command: ["/bin/sh", "-c", 'echo "<h1>${HOSTNAME}</h1>" > /work-dir/index.html']
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}
status: {}
