- hosts: workers
  serial: 1
  become: yes
  become_user: ubuntu
  tasks:
    - name: drain reset delete worker node
      shell: |
        export KUBECONFIG=~/.kube/admin_config.conf
        kubectl drain $(hostname) --ignore-daemonsets > reset.log 2>&1
        sudo kubeadm reset --force >> reset.log 2>&1
        
        # Set the maximum number of attempts
        max_attempts=10
        attempt_num=1
        success=false
        while [ ${success} = false ] && [ ${attempt_num} -le ${max_attempts} ]; do
          echo "try to delete node attempt #: ${attempt_num}"
          kubectl delete node $(hostname) >> reset.log 2>&1
        
          # Check the exit code of the command
          if [ $? -eq 0 ]; then
            # The command was successful
            success=true
          else
            # The command was not successful
            echo "Attempt $attempt_num failed. Trying again..."
            # Increment the attempt counter
            attempt_num=$(( attempt_num + 1 ))
          fi
        done
        
        # Check if the command was successful
        if [ ${success} = true ]; then
          # The command was successful
          echo "The command was successful after $attempt_num attempts."
        else
          # The command was not successful
          echo "The command failed after $max_attempts attempts."
        fi
      args:
        chdir: $HOME
        executable: /usr/bin/bash